In [183]:
import pandas as pd
import numpy as np
import re

In [184]:
df = pd.read_csv("C:\\Users\\soumy\\Downloads\\job-market-analysis\\data\\raw\\internships_raw.csv")

print(df.head())
print(df.info())
print(df.isnull().sum())

             Role Category                   Internship Title  \
0  Data Analyst Internship  Customer Service/Customer Support
1  Data Analyst Internship   Customer Relationship Management
2  Data Analyst Internship  Customer Service/Customer Support
3  Data Analyst Internship                   Customer Success
4  Data Analyst Internship                  Digital Marketing

                                             Company       Location  \
0                                     Paudhewale.com  Not Available
1             Hunarsource Consulting Private Limited  Not Available
2                                           Adda 247  Not Available
3  Genshi Solutions Private Limited (RightChoice.AI)  Not Available
4                                   DataWhiz Academy  Not Available

  Remote Type                                            Stipend  \
0      Onsite  Indore                                        ...
1      Onsite                                               Pune
2      Onsite                                            Lucknow
3      Onsite                                            Gurgaon
4      Onsite                                             Nagpur

                   Duration Posting Date         Skills  \
0  ₹ 10,000 - 13,000 /month  3 weeks ago  Not Available
1    ₹ 7,000 - 8,000 /month  3 weeks ago  Not Available
2            ₹ 5,000 /month  2 weeks ago  Not Available
3  ₹ 15,000 - 20,000 /month  3 weeks ago  Not Available
4   ₹ 3,000 - 10,000 /month  2 weeks ago  Not Available

                                     Internship Link
0  https://internshala.com/internship/detail/cust...
1  https://internshala.com/internship/detail/cust...
2  https://internshala.com/internship/detail/cust...
3  https://internshala.com/internship/detail/cust...
4  https://internshala.com/internship/detail/digi...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Role Category     995 non-null    object
 1   Internship Title  995 non-null    object
 2   Company           995 non-null    object
 3   Location          995 non-null    object
 4   Remote Type       995 non-null    object
 5   Stipend           995 non-null    object
 6   Duration          995 non-null    object
 7   Posting Date      995 non-null    object
 8   Skills            995 non-null    object
 9   Internship Link   995 non-null    object
dtypes: object(10)
memory usage: 77.9+ KB
None
Role Category       0
Internship Title    0
Company             0
Location            0
Remote Type         0
Stipend             0
Duration            0
Posting Date        0
Skills              0
Internship Link     0
dtype: int64

In [185]:
df.head()

,Role Category,Internship Title,Company,Location,Remote Type,Stipend,Duration,Posting Date,Skills,Internship Link
0,Data Analyst Internship,Customer Service/Customer Support,Paudhewale.com,Not Available,Onsite,Indore ...,"₹ 10,000 - 13,000 /month",3 weeks ago,Not Available,https://internshala.com/internship/detail/cust...
1,Data Analyst Internship,Customer Relationship Management,Hunarsource Consulting Private Limited,Not Available,Onsite,Pune,"₹ 7,000 - 8,000 /month",3 weeks ago,Not Available,https://internshala.com/internship/detail/cust...
2,Data Analyst Internship,Customer Service/Customer Support,Adda 247,Not Available,Onsite,Lucknow,"₹ 5,000 /month",2 weeks ago,Not Available,https://internshala.com/internship/detail/cust...
3,Data Analyst Internship,Customer Success,Genshi Solutions Private Limited (RightChoice.AI),Not Available,Onsite,Gurgaon,"₹ 15,000 - 20,000 /month",3 weeks ago,Not Available,https://internshala.com/internship/detail/cust...
4,Data Analyst Internship,Digital Marketing,DataWhiz Academy,Not Available,Onsite,Nagpur,"₹ 3,000 - 10,000 /month",2 weeks ago,Not Available,https://internshala.com/internship/detail/digi...

In [186]:
df.columns = [
    "Role_Category",
    "Internship_Title",
    "Company",
    "Location",
    "Remote_Type",
    "Stipend",
    "Duration",
    "Posting_Date",
    "Skills",
    "Internship_Link"
]

In [187]:
print(df.head())
print(df.shape)
print(df.info())

             Role_Category                   Internship_Title  \
0  Data Analyst Internship  Customer Service/Customer Support
1  Data Analyst Internship   Customer Relationship Management
2  Data Analyst Internship  Customer Service/Customer Support
3  Data Analyst Internship                   Customer Success
4  Data Analyst Internship                  Digital Marketing

                                             Company       Location  \
0                                     Paudhewale.com  Not Available
1             Hunarsource Consulting Private Limited  Not Available
2                                           Adda 247  Not Available
3  Genshi Solutions Private Limited (RightChoice.AI)  Not Available
4                                   DataWhiz Academy  Not Available

  Remote_Type                                            Stipend  \
0      Onsite  Indore                                        ...
1      Onsite                                               Pune
2      Onsite                                            Lucknow
3      Onsite                                            Gurgaon
4      Onsite                                             Nagpur

                   Duration Posting_Date         Skills  \
0  ₹ 10,000 - 13,000 /month  3 weeks ago  Not Available
1    ₹ 7,000 - 8,000 /month  3 weeks ago  Not Available
2            ₹ 5,000 /month  2 weeks ago  Not Available
3  ₹ 15,000 - 20,000 /month  3 weeks ago  Not Available
4   ₹ 3,000 - 10,000 /month  2 weeks ago  Not Available

                                     Internship_Link
0  https://internshala.com/internship/detail/cust...
1  https://internshala.com/internship/detail/cust...
2  https://internshala.com/internship/detail/cust...
3  https://internshala.com/internship/detail/cust...
4  https://internshala.com/internship/detail/digi...
(995, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Role_Category     995 non-null    object
 1   Internship_Title  995 non-null    object
 2   Company           995 non-null    object
 3   Location          995 non-null    object
 4   Remote_Type       995 non-null    object
 5   Stipend           995 non-null    object
 6   Duration          995 non-null    object
 7   Posting_Date      995 non-null    object
 8   Skills            995 non-null    object
 9   Internship_Link   995 non-null    object
dtypes: object(10)
memory usage: 77.9+ KB
None

In [188]:
df.replace("Not Available", np.nan, inplace=True)

C:\Users\soumy\AppData\Local\Temp\ipykernel_18064\941966786.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("Not Available", np.nan, inplace=True)

In [189]:
for col in df.columns:
    df[col] = df[col].astype(str).str.strip()

In [190]:
before = len(df)

df.drop_duplicates(
    subset=[
        "Internship_Title",
        "Company",
        "Location",
        "Stipend",
        "Duration"
    ],
    inplace=True
)

after = len(df)

print(f"Removed {before - after} duplicate rows")

Removed 360 duplicate rows

In [191]:
duplicates = df[
    df.duplicated(
        subset=[
            "Internship_Title",
            "Company",
            "Location"
        ],
        keep=False
    )
]

print(duplicates.head(20))

                         Role_Category        Internship_Title  \
45             Data Science Internship            Data Science
50             Data Science Internship          Data Scientist
76             Data Science Internship            Data Science
86             Data Science Internship          Data Scientist
161        Machine Learning Internship             AI Engineer
169        Machine Learning Internship        Python Developer
177        Machine Learning Internship             AI Engineer
323     Backend Development Internship         Web Development
342     Backend Development Internship  Full Stack Development
373    Frontend Development Internship         Web Development
436  Full Stack Development Internship  Full Stack Development
458  Full Stack Development Internship  Full Stack Development
535                     SQL Internship              QA Testing
537                     SQL Internship          Data Analytics
539                     SQL Internship              QA Testing
586                Power BI Internship          Data Analytics
642        Data Engineering Internship        Python Developer
705          Cyber Security Internship                IT Admin
714          Cyber Security Internship                IT Admin

                                 Company Location Remote_Type  \
45   Maxgen Technologies Private Limited      nan      Onsite
50   Maxgen Technologies Private Limited      nan      Onsite
76   Maxgen Technologies Private Limited      nan      Onsite
86   Maxgen Technologies Private Limited      nan      Onsite
161               TSTEPS PRIVATE LIMITED      nan      Onsite
169  Maxgen Technologies Private Limited      nan      Onsite
177               TSTEPS PRIVATE LIMITED      nan      Onsite
323                                VIZON      nan      Onsite
342               TSTEPS PRIVATE LIMITED      nan      Onsite
373                                VIZON      nan      Onsite
436               TSTEPS PRIVATE LIMITED      nan      Onsite
458               TSTEPS PRIVATE LIMITED      nan      Onsite
535                           Controlled      nan      Onsite
537                  Harshad Enterprises      nan      Onsite
539                           Controlled      nan      Onsite
586                  Harshad Enterprises      nan      Onsite
642  Maxgen Technologies Private Limited      nan      Onsite
705                   JP IT STAFFING LLC      nan      Onsite
714                   JP IT STAFFING LLC      nan      Onsite

                                               Stipend  \
45                                           Ahmedabad
50                                                Pune
76                                                Pune
86                                           Ahmedabad
161  Chennai, Hyderabad                            ...
169                                               Pune
177  Chennai, Mumbai                               ...
323                                Dehradun, Bangalore
342  Chennai, Hyderabad                            ...
373                                     Work from home
436  Chennai, Bangalore                            ...
458  Pondicherry, Kerala Estate                    ...
535                                     Work from home
537                                          Bangalore
539     Gautam Buddha Nagar, Noida, Greater Noida West
586                                          Bangalore
642                                             Rajkot
705                                     Work from home
714                                     Work from home

                     Duration Posting_Date Skills  \
45    ₹ 5,000 - 12,000 /month          nan    nan
50    ₹ 5,000 - 12,000 /month          nan    nan
76    ₹ 5,000 - 12,000 /month          nan    nan
86    ₹ 5,000 - 12,000 /month          nan    nan
161  ₹ 10,000 - 15,000 /month          nan    nan
169   ₹ 5,000 - 12,000 /month          nan    nan
177  ₹ 10,000 - 15,000 /month          nan    nan
323  ₹ 12,000 - 20,000 /month  3 weeks ago    nan
342  ₹ 10,000 - 15,000 /month          nan    nan
373  ₹ 10,000 - 20,000 /month  3 weeks ago    nan
436  ₹ 10,000 - 15,000 /month          nan    nan
458  ₹ 10,000 - 15,000 /month   1 week ago    nan
535    ₹ 2,500 - 5,000 /month          nan    nan
537  ₹ 15,000 - 25,000 /month          nan    nan
539   ₹ 7,000 - 10,000 /month          nan    nan
586  ₹ 20,000 - 25,000 /month  3 weeks ago    nan
642   ₹ 5,000 - 12,000 /month  3 weeks ago    nan
705    ₹ 2,000 - 6,000 /month          nan    nan
714    ₹ 2,000 - 8,000 /month  2 weeks ago    nan

                                       Internship_Link
45   https://internshala.com/internship/detail/data...
50   https://internshala.com/internship/detail/part...
76   https://internshala.com/internship/detail/part...
86   https://internshala.com/internship/detail/data...
161  https://internshala.com/internship/detail/ai-e...
169  https://internshala.com/internship/detail/part...
177  https://internshala.com/internship/detail/ai-e...
323  https://internshala.com/internship/detail/web-...
342  https://internshala.com/internship/detail/full...
373  https://internshala.com/internship/detail/work...
436  https://internshala.com/internship/detail/full...
458  https://internshala.com/internship/detail/full...
535  https://internshala.com/internship/detail/work...
537  https://internshala.com/internship/detail/data...
539  https://internshala.com/internship/detail/qa-t...
586  https://internshala.com/internship/detail/data...
642  https://internshala.com/internship/detail/pyth...
705  https://internshala.com/internship/detail/work...
714  https://internshala.com/internship/detail/work...

In [192]:
print(df.isnull().sum())

Role_Category       0
Internship_Title    0
Company             0
Location            0
Remote_Type         0
Stipend             0
Duration            0
Posting_Date        0
Skills              0
Internship_Link     0
dtype: int64

In [193]:
print(df.dtypes)

Role_Category       object
Internship_Title    object
Company             object
Location            object
Remote_Type         object
Stipend             object
Duration            object
Posting_Date        object
Skills              object
Internship_Link     object
dtype: object

In [194]:
print(df.shape)

print(df.isnull().sum())

print(df.dtypes)

print(df.head())

(635, 10)
Role_Category       0
Internship_Title    0
Company             0
Location            0
Remote_Type         0
Stipend             0
Duration            0
Posting_Date        0
Skills              0
Internship_Link     0
dtype: int64
Role_Category       object
Internship_Title    object
Company             object
Location            object
Remote_Type         object
Stipend             object
Duration            object
Posting_Date        object
Skills              object
Internship_Link     object
dtype: object
             Role_Category                   Internship_Title  \
0  Data Analyst Internship  Customer Service/Customer Support
1  Data Analyst Internship   Customer Relationship Management
2  Data Analyst Internship  Customer Service/Customer Support
3  Data Analyst Internship                   Customer Success
4  Data Analyst Internship                  Digital Marketing

                                             Company Location Remote_Type  \
0                                     Paudhewale.com      nan      Onsite
1             Hunarsource Consulting Private Limited      nan      Onsite
2                                           Adda 247      nan      Onsite
3  Genshi Solutions Private Limited (RightChoice.AI)      nan      Onsite
4                                   DataWhiz Academy      nan      Onsite

                                             Stipend  \
0  Indore                                        ...
1                                               Pune
2                                            Lucknow
3                                            Gurgaon
4                                             Nagpur

                   Duration Posting_Date Skills  \
0  ₹ 10,000 - 13,000 /month  3 weeks ago    nan
1    ₹ 7,000 - 8,000 /month  3 weeks ago    nan
2            ₹ 5,000 /month  2 weeks ago    nan
3  ₹ 15,000 - 20,000 /month  3 weeks ago    nan
4   ₹ 3,000 - 10,000 /month  2 weeks ago    nan

                                     Internship_Link
0  https://internshala.com/internship/detail/cust...
1  https://internshala.com/internship/detail/cust...
2  https://internshala.com/internship/detail/cust...
3  https://internshala.com/internship/detail/cust...
4  https://internshala.com/internship/detail/digi...

In [195]:
# Create corrected columns

df["Correct_Location"] = df["Stipend"]

df["Correct_Stipend"] = df["Duration"]

df["Correct_Posting_Date"] = df["Posting_Date"]

In [196]:
df.head()

,Role_Category,Internship_Title,Company,Location,Remote_Type,Stipend,Duration,Posting_Date,Skills,Internship_Link,Correct_Location,Correct_Stipend,Correct_Posting_Date
0,Data Analyst Internship,Customer Service/Customer Support,Paudhewale.com,nan,Onsite,Indore ...,"₹ 10,000 - 13,000 /month",3 weeks ago,nan,https://internshala.com/internship/detail/cust...,Indore ...,"₹ 10,000 - 13,000 /month",3 weeks ago
1,Data Analyst Internship,Customer Relationship Management,Hunarsource Consulting Private Limited,nan,Onsite,Pune,"₹ 7,000 - 8,000 /month",3 weeks ago,nan,https://internshala.com/internship/detail/cust...,Pune,"₹ 7,000 - 8,000 /month",3 weeks ago
2,Data Analyst Internship,Customer Service/Customer Support,Adda 247,nan,Onsite,Lucknow,"₹ 5,000 /month",2 weeks ago,nan,https://internshala.com/internship/detail/cust...,Lucknow,"₹ 5,000 /month",2 weeks ago
3,Data Analyst Internship,Customer Success,Genshi Solutions Private Limited (RightChoice.AI),nan,Onsite,Gurgaon,"₹ 15,000 - 20,000 /month",3 weeks ago,nan,https://internshala.com/internship/detail/cust...,Gurgaon,"₹ 15,000 - 20,000 /month",3 weeks ago
4,Data Analyst Internship,Digital Marketing,DataWhiz Academy,nan,Onsite,Nagpur,"₹ 3,000 - 10,000 /month",2 weeks ago,nan,https://internshala.com/internship/detail/digi...,Nagpur,"₹ 3,000 - 10,000 /month",2 weeks ago

In [197]:
df.drop(
    columns=[
        "Location",
        "Stipend",
        "Duration",
        "Posting_Date",
        "Skills"
    ],
    inplace=True
)

In [198]:
df.head()

,Role_Category,Internship_Title,Company,Remote_Type,Internship_Link,Correct_Location,Correct_Stipend,Correct_Posting_Date
0,Data Analyst Internship,Customer Service/Customer Support,Paudhewale.com,Onsite,https://internshala.com/internship/detail/cust...,Indore ...,"₹ 10,000 - 13,000 /month",3 weeks ago
1,Data Analyst Internship,Customer Relationship Management,Hunarsource Consulting Private Limited,Onsite,https://internshala.com/internship/detail/cust...,Pune,"₹ 7,000 - 8,000 /month",3 weeks ago
2,Data Analyst Internship,Customer Service/Customer Support,Adda 247,Onsite,https://internshala.com/internship/detail/cust...,Lucknow,"₹ 5,000 /month",2 weeks ago
3,Data Analyst Internship,Customer Success,Genshi Solutions Private Limited (RightChoice.AI),Onsite,https://internshala.com/internship/detail/cust...,Gurgaon,"₹ 15,000 - 20,000 /month",3 weeks ago
4,Data Analyst Internship,Digital Marketing,DataWhiz Academy,Onsite,https://internshala.com/internship/detail/digi...,Nagpur,"₹ 3,000 - 10,000 /month",2 weeks ago

In [199]:
df.rename(
    columns={
        "Correct_Location": "Location",
        "Correct_Stipend": "Stipend",
        "Correct_Posting_Date": "Posting_Date"
    },
    inplace=True
)

In [200]:
print(df.head())
print(df.columns)
print(df.shape)

             Role_Category                   Internship_Title  \
0  Data Analyst Internship  Customer Service/Customer Support
1  Data Analyst Internship   Customer Relationship Management
2  Data Analyst Internship  Customer Service/Customer Support
3  Data Analyst Internship                   Customer Success
4  Data Analyst Internship                  Digital Marketing

                                             Company Remote_Type  \
0                                     Paudhewale.com      Onsite
1             Hunarsource Consulting Private Limited      Onsite
2                                           Adda 247      Onsite
3  Genshi Solutions Private Limited (RightChoice.AI)      Onsite
4                                   DataWhiz Academy      Onsite

                                     Internship_Link  \
0  https://internshala.com/internship/detail/cust...
1  https://internshala.com/internship/detail/cust...
2  https://internshala.com/internship/detail/cust...
3  https://internshala.com/internship/detail/cust...
4  https://internshala.com/internship/detail/digi...

                                            Location  \
0  Indore                                        ...
1                                               Pune
2                                            Lucknow
3                                            Gurgaon
4                                             Nagpur

                    Stipend Posting_Date
0  ₹ 10,000 - 13,000 /month  3 weeks ago
1    ₹ 7,000 - 8,000 /month  3 weeks ago
2            ₹ 5,000 /month  2 weeks ago
3  ₹ 15,000 - 20,000 /month  3 weeks ago
4   ₹ 3,000 - 10,000 /month  2 weeks ago
Index(['Role_Category', 'Internship_Title', 'Company', 'Remote_Type',
       'Internship_Link', 'Location', 'Stipend', 'Posting_Date'],
      dtype='object')
(635, 8)

In [201]:
df["Duration"] = np.nan

In [202]:
df["Location"] = (
    df["Location"]
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.strip()
)

In [203]:
df["Remote_Type"] = (
    df["Remote_Type"]
    .str.title()
    .str.strip()
)

In [204]:
print(df["Remote_Type"].unique())

['Onsite']

In [205]:
print(df["Remote_Type"].value_counts())

Remote_Type
Onsite    635
Name: count, dtype: int64

In [206]:
def extract_stipend(stipend):

    if pd.isna(stipend):
        return pd.Series([None, None, None])

    stipend = str(stipend)

    # Extract full Indian-formatted numbers
    numbers = re.findall(r'[\d,]+', stipend)

    cleaned_numbers = []

    for num in numbers:

        try:
            cleaned_numbers.append(
                int(num.replace(",", ""))
            )

        except:
            continue

    if len(cleaned_numbers) == 1:

        value = cleaned_numbers[0]

        return pd.Series([
            value,
            value,
            value
        ])

    elif len(cleaned_numbers) >= 2:

        min_value = cleaned_numbers[0]
        max_value = cleaned_numbers[1]

        avg_value = (
            min_value + max_value
        ) / 2

        return pd.Series([
            min_value,
            max_value,
            avg_value
        ])

    return pd.Series([None, None, None])

In [207]:
df[
    [
        "Min_Stipend",
        "Max_Stipend",
        "Avg_Stipend"
    ]
] = df["Stipend"].apply(extract_stipend)

In [208]:
print(
    df[
        [
            "Stipend",
            "Min_Stipend",
            "Max_Stipend",
            "Avg_Stipend"
        ]
    ].head(20)
)

                     Stipend  Min_Stipend  Max_Stipend  Avg_Stipend
0   ₹ 10,000 - 13,000 /month      10000.0      13000.0      11500.0
1     ₹ 7,000 - 8,000 /month       7000.0       8000.0       7500.0
2             ₹ 5,000 /month       5000.0       5000.0       5000.0
3   ₹ 15,000 - 20,000 /month      15000.0      20000.0      17500.0
4    ₹ 3,000 - 10,000 /month       3000.0      10000.0       6500.0
5     ₹ 5,000 - 7,000 /month       5000.0       7000.0       6000.0
6     ₹ 3,500 - 6,000 /month       3500.0       6000.0       4750.0
7   ₹ 10,000 - 15,000 /month      10000.0      15000.0      12500.0
8   ₹ 18,000 - 30,000 /month      18000.0      30000.0      24000.0
9        Competitive stipend          NaN          NaN          NaN
10                       nan          NaN          NaN          NaN
11   ₹ 5,000 - 10,000 /month       5000.0      10000.0       7500.0
12       Competitive stipend          NaN          NaN          NaN
13    ₹ 4,000 - 5,000 /month       4000.0       5000.0       4500.0
14                    Unpaid          NaN          NaN          NaN
15   ₹ 9,000 - 20,000 /month       9000.0      20000.0      14500.0
16   ₹ 5,000 - 10,000 /month       5000.0      10000.0       7500.0
17  ₹ 26,000 - 37,000 /month      26000.0      37000.0      31500.0
18   ₹ 8,000 - 14,000 /month       8000.0      14000.0      11000.0
19           ₹ 10,000 /month      10000.0      10000.0      10000.0

In [209]:
def stipend_type(stipend):

    stipend = str(stipend).lower()

    if "unpaid" in stipend:
        return "Unpaid"

    elif "competitive" in stipend:
        return "Competitive"

    elif "nan" in stipend:
        return "Missing"

    return "Paid"

In [210]:
df["Stipend_Type"] = (
    df["Stipend"]
    .apply(stipend_type)
)

In [211]:
print(df["Stipend_Type"].value_counts())

Stipend_Type
Paid           603
Unpaid          23
Competitive      8
Missing          1
Name: count, dtype: int64

In [212]:
df = df.dropna(
    subset=["Posting_Date"]
)

In [213]:
print(df.shape)

print(df.isnull().sum())

print(df.head())

print(df.describe())

(635, 13)
Role_Category         0
Internship_Title      0
Company               0
Remote_Type           0
Internship_Link       0
Location              0
Stipend               0
Posting_Date          0
Duration            635
Min_Stipend          33
Max_Stipend          33
Avg_Stipend          33
Stipend_Type          0
dtype: int64
             Role_Category                   Internship_Title  \
0  Data Analyst Internship  Customer Service/Customer Support
1  Data Analyst Internship   Customer Relationship Management
2  Data Analyst Internship  Customer Service/Customer Support
3  Data Analyst Internship                   Customer Success
4  Data Analyst Internship                  Digital Marketing

                                             Company Remote_Type  \
0                                     Paudhewale.com      Onsite
1             Hunarsource Consulting Private Limited      Onsite
2                                           Adda 247      Onsite
3  Genshi Solutions Private Limited (RightChoice.AI)      Onsite
4                                   DataWhiz Academy      Onsite

                                     Internship_Link  \
0  https://internshala.com/internship/detail/cust...
1  https://internshala.com/internship/detail/cust...
2  https://internshala.com/internship/detail/cust...
3  https://internshala.com/internship/detail/cust...
4  https://internshala.com/internship/detail/digi...

                                            Location  \
0  Indore                                        ...
1                                               Pune
2                                            Lucknow
3                                            Gurgaon
4                                             Nagpur

                    Stipend Posting_Date  Duration  Min_Stipend  Max_Stipend  \
0  ₹ 10,000 - 13,000 /month  3 weeks ago       NaN      10000.0      13000.0
1    ₹ 7,000 - 8,000 /month  3 weeks ago       NaN       7000.0       8000.0
2            ₹ 5,000 /month  2 weeks ago       NaN       5000.0       5000.0
3  ₹ 15,000 - 20,000 /month  3 weeks ago       NaN      15000.0      20000.0
4   ₹ 3,000 - 10,000 /month  2 weeks ago       NaN       3000.0      10000.0

   Avg_Stipend Stipend_Type
0      11500.0         Paid
1       7500.0         Paid
2       5000.0         Paid
3      17500.0         Paid
4       6500.0         Paid
       Duration   Min_Stipend    Max_Stipend    Avg_Stipend
count       0.0    602.000000     602.000000     602.000000
mean        NaN   9561.131229   15119.127907   12340.129568
std         NaN   8244.256944   12599.188017    9992.345719
min         NaN    600.000000    1000.000000     800.000000
25%         NaN   5000.000000    8625.000000    7500.000000
50%         NaN   9000.000000   12250.500000   11000.000000
75%         NaN  10000.000000   20000.000000   15000.000000
max         NaN  75000.000000  125000.000000  100000.000000

In [214]:
df.drop(
    columns=["Duration"],
    inplace=True
)

In [215]:
df["Location"] = (
    df["Location"]
    .astype(str)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [216]:
df["Posting_Days_Ago"] = (
    df["Posting_Date"]
    .apply(convert_posting_days)
)

In [217]:
print(
    df[
        ["Posting_Date", "Posting_Days_Ago"]
    ].head(20)
)

   Posting_Date  Posting_Days_Ago
0   3 weeks ago              21.0
1   3 weeks ago              21.0
2   2 weeks ago              14.0
3   3 weeks ago              21.0
4   2 weeks ago              14.0
5   3 weeks ago              21.0
6   3 weeks ago              21.0
7   3 weeks ago              21.0
8   3 weeks ago              21.0
9   3 weeks ago              21.0
10          nan               NaN
11  3 weeks ago              21.0
12  3 weeks ago              21.0
13  3 weeks ago              21.0
14  2 weeks ago              14.0
15  3 weeks ago              21.0
16  2 weeks ago              14.0
17  3 weeks ago              21.0
18  3 weeks ago              21.0
19  3 weeks ago              21.0

In [218]:
print(
    df.sort_values(
        by="Avg_Stipend",
        ascending=False
    ).head(10)
)

                       Role_Category  \
723                DevOps Internship
687       Cloud Computing Internship
702        Cyber Security Internship
134      Machine Learning Internship
157      Machine Learning Internship
406  Frontend Development Internship
313   Backend Development Internship
965     Digital Marketing Internship
584              Power BI Internship
580              Power BI Internship

                                      Internship_Title  \
723                            GUI Automation Engineer
687                      Platform And Backend Engineer
702                               Cybersecurity Mentor
134                             Full Stack AI Engineer
157                                       AI/ML Mentor
406  Coding Instructor | Mentor | Data Structures &...
313                                    Web Development
965         Founders Office Intern (3 Months) — Remote
584                                     Data Analytics
580                                     Data Analytics

                                 Company Remote_Type  \
723                         DeepMechanix      Onsite
687                         DeepMechanix      Onsite
702                        CipherSchools      Onsite
134                  Techsolv IT Service      Onsite
157                        CipherSchools      Onsite
406                        CipherSchools      Onsite
313                               Artify      Onsite
965                              Inturol      Onsite
584  Calipers Consulting Private Limited      Onsite
580                            Venkatesh      Onsite

                                       Internship_Link  \
723  https://internshala.com/internship/detail/work...
687  https://internshala.com/internship/detail/work...
702  https://internshala.com/internship/detail/cybe...
134  https://internshala.com/internship/detail/work...
157  https://internshala.com/internship/detail/ai-m...
406  https://internshala.com/internship/detail/codi...
313  https://internshala.com/internship/detail/work...
965  https://internshala.com/internship/detail/work...
584  https://internshala.com/internship/detail/data...
580  https://internshala.com/internship/detail/data...

                                              Location  \
723                                     Work from home
687                                     Work from home
702          Chandigarh, Delhi, Gurgaon, Noida, Punjab
134                                     Work from home
157          Delhi, Gurgaon, Noida, Chandigarh, Punjab
406  Chandigarh, Delhi, Gurgaon, Mohali, Noida, Punjab
313                                     Work from home
965                                     Work from home
584                   Secunderabad, Hyderabad (Hybrid)
580                   Secunderabad, Hyderabad (Hybrid)

                        Stipend Posting_Date  Min_Stipend  Max_Stipend  \
723  ₹ 75,000 - 1,25,000 /month  3 weeks ago      75000.0     125000.0
687  ₹ 75,000 - 1,25,000 /month  3 weeks ago      75000.0     125000.0
702    ₹ 60,000 - 80,000 /month          nan      60000.0      80000.0
134    ₹ 60,000 - 80,000 /month          nan      60000.0      80000.0
157    ₹ 60,000 - 80,000 /month          nan      60000.0      80000.0
406    ₹ 60,000 - 80,000 /month   1 week ago      60000.0      80000.0
313    ₹ 45,000 - 70,000 /month  2 weeks ago      45000.0      70000.0
965             ₹ 50,000 /month   1 week ago      50000.0      50000.0
584    ₹ 40,000 - 50,000 /month  3 weeks ago      40000.0      50000.0
580    ₹ 40,000 - 50,000 /month  2 weeks ago      40000.0      50000.0

     Avg_Stipend Stipend_Type  Posting_Days_Ago
723     100000.0         Paid              21.0
687     100000.0         Paid              21.0
702      70000.0         Paid               NaN
134      70000.0         Paid               NaN
157      70000.0         Paid               NaN
406      70000.0         Paid               7.0
313      57500.0         Paid              14.0
965      50000.0         Paid               7.0
584      45000.0         Paid              21.0
580      45000.0         Paid              14.0

In [219]:
print(
    df.sort_values(
        by="Avg_Stipend",
        ascending=False
    ).head(10)
)

                       Role_Category  \
723                DevOps Internship
687       Cloud Computing Internship
702        Cyber Security Internship
134      Machine Learning Internship
157      Machine Learning Internship
406  Frontend Development Internship
313   Backend Development Internship
965     Digital Marketing Internship
584              Power BI Internship
580              Power BI Internship

                                      Internship_Title  \
723                            GUI Automation Engineer
687                      Platform And Backend Engineer
702                               Cybersecurity Mentor
134                             Full Stack AI Engineer
157                                       AI/ML Mentor
406  Coding Instructor | Mentor | Data Structures &...
313                                    Web Development
965         Founders Office Intern (3 Months) — Remote
584                                     Data Analytics
580                                     Data Analytics

                                 Company Remote_Type  \
723                         DeepMechanix      Onsite
687                         DeepMechanix      Onsite
702                        CipherSchools      Onsite
134                  Techsolv IT Service      Onsite
157                        CipherSchools      Onsite
406                        CipherSchools      Onsite
313                               Artify      Onsite
965                              Inturol      Onsite
584  Calipers Consulting Private Limited      Onsite
580                            Venkatesh      Onsite

                                       Internship_Link  \
723  https://internshala.com/internship/detail/work...
687  https://internshala.com/internship/detail/work...
702  https://internshala.com/internship/detail/cybe...
134  https://internshala.com/internship/detail/work...
157  https://internshala.com/internship/detail/ai-m...
406  https://internshala.com/internship/detail/codi...
313  https://internshala.com/internship/detail/work...
965  https://internshala.com/internship/detail/work...
584  https://internshala.com/internship/detail/data...
580  https://internshala.com/internship/detail/data...

                                              Location  \
723                                     Work from home
687                                     Work from home
702          Chandigarh, Delhi, Gurgaon, Noida, Punjab
134                                     Work from home
157          Delhi, Gurgaon, Noida, Chandigarh, Punjab
406  Chandigarh, Delhi, Gurgaon, Mohali, Noida, Punjab
313                                     Work from home
965                                     Work from home
584                   Secunderabad, Hyderabad (Hybrid)
580                   Secunderabad, Hyderabad (Hybrid)

                        Stipend Posting_Date  Min_Stipend  Max_Stipend  \
723  ₹ 75,000 - 1,25,000 /month  3 weeks ago      75000.0     125000.0
687  ₹ 75,000 - 1,25,000 /month  3 weeks ago      75000.0     125000.0
702    ₹ 60,000 - 80,000 /month          nan      60000.0      80000.0
134    ₹ 60,000 - 80,000 /month          nan      60000.0      80000.0
157    ₹ 60,000 - 80,000 /month          nan      60000.0      80000.0
406    ₹ 60,000 - 80,000 /month   1 week ago      60000.0      80000.0
313    ₹ 45,000 - 70,000 /month  2 weeks ago      45000.0      70000.0
965             ₹ 50,000 /month   1 week ago      50000.0      50000.0
584    ₹ 40,000 - 50,000 /month  3 weeks ago      40000.0      50000.0
580    ₹ 40,000 - 50,000 /month  2 weeks ago      40000.0      50000.0

     Avg_Stipend Stipend_Type  Posting_Days_Ago
723     100000.0         Paid              21.0
687     100000.0         Paid              21.0
702      70000.0         Paid               NaN
134      70000.0         Paid               NaN
157      70000.0         Paid               NaN
406      70000.0         Paid               7.0
313      57500.0         Paid              14.0
965      50000.0         Paid               7.0
584      45000.0         Paid              21.0
580      45000.0         Paid              14.0

In [220]:
df["Location"] = (
    df["Location"]
    .astype(str)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [221]:
def extract_city_workmode(location, remote_type):

    location = str(location)

    remote_type = str(remote_type)

    # Hybrid case
    if "(" in location:

        parts = location.split("(")

        city = parts[0].strip()

        work_mode = (
            parts[1]
            .replace(")", "")
            .strip()
        )

        return pd.Series([city, work_mode])

    # Work from home case
    elif "work from home" in location.lower():

        return pd.Series([
            "Remote",
            "Remote"
        ])

    # Default fallback
    return pd.Series([
        location,
        remote_type
    ])

In [222]:
df[
    [
        "City",
        "Work_Mode"
    ]
] = df.apply(
    lambda row:
    extract_city_workmode(
        row["Location"],
        row["Remote_Type"]
    ),
    axis=1
)

In [230]:
df.to_csv(
    r"C:\Users\soumy\Downloads\job-market-analysis\data\Cleaned\internships_cleaned.csv",
    index=False
)

In [229]:
df.head()

,Role_Category,Internship_Title,Company,Internship_Link,Location,Stipend,Posting_Date,Min_Stipend,Max_Stipend,Avg_Stipend,Stipend_Type,Posting_Days_Ago,City,Work_Mode
0,Data Analyst Internship,Customer Service/Customer Support,Paudhewale.com,https://internshala.com/internship/detail/cust...,Indore (Hybrid),"₹ 10,000 - 13,000 /month",3 weeks ago,10000.0,13000.0,11500.0,Paid,21.0,Indore,Hybrid
1,Data Analyst Internship,Customer Relationship Management,Hunarsource Consulting Private Limited,https://internshala.com/internship/detail/cust...,Pune,"₹ 7,000 - 8,000 /month",3 weeks ago,7000.0,8000.0,7500.0,Paid,21.0,Pune,Onsite
2,Data Analyst Internship,Customer Service/Customer Support,Adda 247,https://internshala.com/internship/detail/cust...,Lucknow,"₹ 5,000 /month",2 weeks ago,5000.0,5000.0,5000.0,Paid,14.0,Lucknow,Onsite
3,Data Analyst Internship,Customer Success,Genshi Solutions Private Limited (RightChoice.AI),https://internshala.com/internship/detail/cust...,Gurgaon,"₹ 15,000 - 20,000 /month",3 weeks ago,15000.0,20000.0,17500.0,Paid,21.0,Gurgaon,Onsite
4,Data Analyst Internship,Digital Marketing,DataWhiz Academy,https://internshala.com/internship/detail/digi...,Nagpur,"₹ 3,000 - 10,000 /month",2 weeks ago,3000.0,10000.0,6500.0,Paid,14.0,Nagpur,Onsite

In [227]:
df.drop(
    columns=["Remote_Type"],
    inplace=True
)

In [228]:
df.dropna(
    subset=[
        "Internship_Title",
        "Company",
        "Location",
        "Internship_Link"
    ],
    inplace=True
)